### ISSUE TITLE
Cant use this

### ISSUE THREAD

**Issue by absoluttechno** [ioncodes/JodelAPI#1]
cann you make an build of this in .exe? i can't start it with visualstudio and can't load this shit. please make a executable version

**Comment by absoluttechno** [comment]
Ich schaffe es einfach nicht zu builden, kannst du mir echt helfen ?

**Comment by ioncodes** [comment]
There are Projects: Console, Library, and Unit Tests. You need to build the Library (JodelAPI Project). Just open the sln and compile the library or open the csproj and compile the libary directly.

**Comment by absoluttechno** [comment]
But where can i edit for setup?

Please i'm newbie can you expöain from the beginning till the end to get this working

**Comment by ioncodes** [comment]
https://msdn.microsoft.com/en-us/library/3w7axy17.aspx

**Comment by absoluttechno** [comment]
Do you speak german?

**Comment by ioncodes** [comment]
Due to your rude language and behavior I will close the Issue now. To learn how to compile a Visual Studio Solution, please refer to the official Microsoft Documentation:  https://msdn.microsoft.com/en-us/library/5tdasz7h.aspx

Or use Google: http://lmgtfy.com/?q=how+to+compile+a+.sln+file

If you have problems with cloning a git repo refer to this: http://lmgtfy.com/?q=how+to+clone+git+repository

If you don't understand what a library is, start here: http://lmgtfy.com/?q=What+is+a+class+library%3F

For other questions refer to Google or Stackoverflow.

Thank you
